### ISSUE TITLE
Make brand new Tapyrus Network possible to start with arguments

### ISSUE THREAD

**Issue by rantan** [chaintope/tapyrus-core#17]
Regarding consensus part, which means genesis block and aggregated public key,  parameters are got as arguments. However, regarding network part, there are more elements to be set as argument for start brand new network without changing some codes.

These elements should be got as arguments of tapyrus core.

* Magic bytes
* seeds

Probably [tapyrus-seeder](https://github.com/chaintope/tapyrus-seeder) is also needed to be changed for this. We should test it.

**Comment by Naviabheeman** [comment]
There are some more things to consider
1. Some of these parameters are variable in the software point of view but fixed per network/federation throughput its lifetime. These have to configurable before setting up the network, but fixed and Immutable after the network has started.

- Genesis block
- Network id. magic bytes can be calculated from network id.
- Address prefix, public key & private key prefix, WIF prefix

2. Do we need different network modes - testnet, mainnet and regtest for each federation?
 Then the  network id will represent a federation. Other parameters above have to be different for each mode.

3. Other options that we can configure per node in the config file
- DNS seeder host name
- ServiceFlags (now this is determined by the version of software)

**Comment by azuchi** [comment]
> Do we need different network modes - testnet, mainnet and regtest for each federation?

I think, it is not necessary to separate mainnet and testnet because the network can be configured. However, regtest is necessary in the sense that it can create a signature by itself.

> 3. Other options that may change every time a node restarts which are not in the config file now are:

DNS seeder host name must be configurable for each network.

I think that ServiceFlag can be used as it is. Do you have any idea?

**Comment by Naviabheeman** [comment]
> 
> DNS seeder host name must be configurable for each network.
>
ok. Then we cannot run multiple DNS seeders? 

> I think that ServiceFlag can be used as it is. Do you have any idea?

I was thinking that we can add all components of tapyrus as a service, for example when we have index server it can be a new service.  Nodes may add or remove a service at any time and the dns seeder can be extended to track all.

**Comment by azuchi** [comment]
> Then we cannot run multiple DNS seeders?
Basically we launch one seeder, but multiple seeder can run.

> Nodes may add or remove a service at any time and the dns seeder can be extended to track all.
ok. The Service flag can now be specified with a command line option.  Let's leave it as it is.

**Comment by Naviabheeman** [comment]
Tapyrus reads genesis.dat and Config file from data directory. After implementing networkId we might have multiple networks in mainnet mode, testnet mode and regtest. So we have to add network ids into the directory name. 

Currently when starting in -testnet and -regtest modes, a sub directory with this name is created inside data dir and blocks are put inside the subdirectory.

1) I am changing the directory name to `<chain>-<networkId>` _e.g main-1, test-1939510133_
2) Rename genesis.dat to `genesis.<networkId>` to support multiple genesis block files _e.g genesis.1, genesis.1939510133_

**Comment by azuchi** [comment]
I think only two modes, mainnet and regtest, are enough. testnet is not necessary.

Agree on changing dir name and geneesis file name.

**Comment by Naviabheeman** [comment]
In testnet mode these two parameters are different from mainnet:
1. acceptnonstdtxn is true by default. 
2. fallbackfee is enabled.
When starting a new network for testing we need to change these to get the old testnet behaviour.

**Comment by azuchi** [comment]
Let's remove the difference from testnet mode.

In Tapyrus, unlike Bitcoin, the test environment should have no difference in operation from the mainnet environment.

**Comment by Naviabheeman** [comment]
I created first PR under this task,  #37.

I have some more questions:
1. Since we have only two modes, using the names main and regtest is confusing, can we rename it to "ONLINE & OFFLINE" or "LIVE & PASSIVE" instead?
2. Should we make base 58 prefixes (for public key, private key, address) dependent on networkId? Now it is based on mainnet or regtest.
3. DNS Seeder name and list of fixed seed nodes should both be command line options?

**Comment by azuchi** [comment]
> Since we have only two modes, using the names main and regtest is confusing, can we rename it to "ONLINE & OFFLINE" or "LIVE & PASSIVE" instead?

regtest also can connect other node, so online too. How about `production(prod)` and `development(dev)`?

> Should we make base 58 prefixes (for public key, private key, address) dependent on networkId? Now it is based on mainnet or regtest.

It's a wallet-related feature, so let's leave it for now. Because it may affect other wallet libraries.

> DNS Seeder name and list of fixed seed nodes should both be command line options?

yes. Each seeder will configured for each network, so it specified by command line option or configuration file.
