### ISSUE TITLE
Add new xfield type to change max block size

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-core#231]
The block size is currently fixed at 1MB (the implementation defines it as 4MB in weight equivalent), but to allow this size to be changed, the following new xfield type is introduced:

* xfield type: 2
* xfield value: max block size(bytes) with 4-byte hex value.

If this xfield type is specified in the block header, the new maximum block size is applied starting with the next block, if that value is valid.

**Comment by Naviabheeman** [comment]
1. Due to **MAX_PROTOCOL_MESSAGE_LENGTH** set to 4 MB two nodes are not able to synch blocks larger than that.  The p2p message is not split into multiple messages when its size is large.  I changed this limit to 10 MB and ran the test. Nodes are able to create large blocks upto 10 MB and synch with each other. Blocks with non standard sigops and non standard transaction size are also accepted. How do me handle this limitation, can we make it a cmd line option so that we can restart a node with new message length if the block size changes or make this also dependant on block size?

2. When a node restarts after a block changing the block size limit in some cases it needs to be restarted with -reindex option. For example, let B30 be the block setting xfield max block size to 4 MB. Then B31, B32 are blocks of large size. IF the node restarts at this point, there is code to VeridyDB() which validated the last 6 blocks in reverse order. i.e. B32 would be checked first and at that point federation params contains only the old block size limit. So the validation fails. These are the logs from this scenario.

'2022-11-23T12:38:20Z Loaded best chain: hashBestChain=54f69a7f6365a0b8fdbce8f3e53bf98a23bdb131dfd479eb76907b689d86941b height=318 date=2022-11-23T12:11:09Z progress=1.000000
2022-11-23T12:38:20Z init message: Rewinding blocks...
2022-11-23T12:38:20Z init message: Verifying blocks...
2022-11-23T12:39:04Z Verifying last 6 blocks at level 3
2022-11-23T12:39:16Z [0%]...[16%]...[33%]...ERROR: VerifyDB: *** found bad block at 316, hash=221b92c7c660293cd2ae71ef10a56ccadf7d6db4464775f1770aa892f9dacd17 (bad-blk-length, size limits failed (code 16))

2022-11-23T12:48:02Z : Corrupted block database detected.
Please restart with -reindex or -reindex-chainstate to recover.
: Corrupted block database detected.'

Restarting the node with -reindex works fine. The node is able to start and synch to the latest block.

**Comment by azuchi** [comment]
About no.1: if the block size specified in xfield is greater than `MAX_PROTOCOL_MESSAGE_LENGTH`, is it possible to dynamically change this parameter to the value specified in xfield (the minimum value remains at its current value)?

About no.2: If the block size is changed with the xfield type, where is the target block height and change size information stored? If these are kept, can we specify the block size that should be checked on the target block in the check in VerifyDB?

**Comment by Naviabheeman** [comment]
> About no.1: if the block size specified in xfield is greater than `MAX_PROTOCOL_MESSAGE_LENGTH`, is it possible to dynamically change this parameter to the value specified in xfield (the minimum value remains at its current value)?
>
MAX_PROTOCOL_MESSAGE_LENGTH is a constant. But its usage in the protocol layer is just a comparison to message length. I can change this to use xfield block size if that is higher.

> About no.2: If the block size is changed with the xfield type, where is the target block height and change size information stored? If these are kept, can we specify the block size that should be checked on the target block in the check in VerifyDB?
The changes in max block size and block height are kept in federation params. But in Verify DB the verification happens in reverse, the bigger block comes before the block with xfield to update max block size. So verification fails. I'll try to dig in further and see what can be done.

**Comment by azuchi** [comment]
> MAX_PROTOCOL_MESSAGE_LENGTH is a constant. But its usage in the protocol layer is just a comparison to message length. I can change this to use xfield block size if that is higher.

Let's apply this change.

> The changes in max block size and block height are kept in federation params. But in Verify DB the verification happens in reverse, the bigger block comes before the block with xfield to update max block size. So verification fails. I'll try to dig in further and see what can be done.

When is the new block size saved as a federation parameter? if it is saved as a federation parameter when B30 is processed, can't we use it for B32 verification after node restart?

**Comment by Naviabheeman** [comment]
PR 234 implements the generic xfield for max block size. 
It ports the fixes from v0.5.2 for errors mentioned here with node restart, new node addition and block verification.
