### ISSUE TITLE
Support basic transfer with tapyrus-qt

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-core#51]
Start tapyrus-qt and do the following:

・ Chain synchronization
・ Coin sending and receiving

**Comment by Naviabheeman** [comment]
I tried to test Tapyrus-qt and below are my observations:
1. Tapyrus-qt from the master branch (version 0.4.0) **_CANNOT_** be used to create a new node to tapyrus testnet(version 0.3.0 ). Chain synchronisation is successful with the correct networkid and port number configuration. But Send and receive coin cannot be performed from GUI. This is because the public key, WIF, address prefix do not match. (In 0.4.0 we removed 'testnet' mode that is used by 0.3.0 testnet and all related parameters)
2. **Chain synchronisation is successful** in a custom network(0.4.0) as well as testnet(0.3.0)
3. Send and receive can be performed successfully in a custom network. There are some failures described below. (Tested using two nodes, one GUI and cmd line.)

Overview tab: 

- Available and Pending balances are updated as expected.
- [ ] **Remove Immature balance**

Send coins Tab:

- Sending transaction with **"Custom"** fee is successful. 
- When node does not have **_-fallbackfee_** configured, transaction creation with **_"Recommended"_** fee  is not successful. It fails with error  "Fee estimation failed. Fallbackfee is disabled. Wait a few blocks or enable -fallbackfee."

Receive Tab:

- The address generated is native as expected. URI and QR code are not verified.

> Payment information
URI: tapyrus:18UGvudbhujUHw3gNuBaugXAewGttubSCf?amount=1.00000000
Address: 18UGvudbhujUHw3gNuBaugXAewGttubSCf
Amount: 1.00000000 TPC

- [ ] **Remove option "Generate native segwit(bech32) address".** ( GUI crashes when we try to "Request payment" with this option set)

Transactions tab:

- Transaction list and filtering are working as expected. 
- We need to update Type lable "Mined" and icons representing transaction spendability(clock symbol until 6 confirmations)

**Comment by Naviabheeman** [comment]
Changes mentioned above are in https://github.com/chaintope/tapyrus-core/pull/58
